# Generated by Django 4.2.2 on 2023-06-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '4. Course'},
        ),
        migrations.AlterModelOptions(
            name='coursecatalog',
            options={'verbose_name': '3. Course Catalog'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': '2. Instructor'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '1. Student'},
        ),
    ]
